spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/notification
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create #create update none
    properties:
      hibernate:
        format_sql: true
#    show-sql: true

logging.level:
  org.hibernate.SQL: debug

telegram:
  bot:
    token: 6606545210:AAFixMN2CinSKLRlUdr8iFoujLtGHNYns3s
  chat:
    id: 6681463974